#
# Copyright 2015-2018 Micro Focus or one of its affiliates.
#
# The only warranties for products and services of Micro Focus and its
# affiliates and licensors ("Micro Focus") are set forth in the express
# warranty statements accompanying such products and services. Nothing
# herein should be construed as constituting an additional warranty.
# Micro Focus shall not be liable for technical or editorial errors or
# omissions contained herein. The information contained herein is subject
# to change without notice.
#
# Contains Confidential Information. Except as specifically indicated
# otherwise, a valid license is required for possession, use or copying.
# Consistent with FAR 12.211 and 12.212, Commercial Computer Software,
# Computer Software Documentation, and Technical Data for Commercial
# Items are licensed to the U.S. Government under vendor's standard
# commercial license.
#

debug: false
server:
  port: 8080
https:
  port: 8443
management:
  server:
    port: 8081
  endpoints:
    web:
      base-path: /
      path-mapping:
        health: healthcheck
  endpoint:
    health:
      show-details: ALWAYS
    info:
      enabled: false
spring:
  servlet:
    multipart:
      enabled: true
staging:
    basePath: ${CAF_STAGING_SERVICE_BASEPATH:/staging-service}
    subbatchSize: ${CAF_STAGING_SERVICE_SUBBATCH_SIZE:250}
logging:
  level:
    ROOT: ${CAF_LOG_LEVEL:WARN}
    org.springframework: ${CAF_STAGING_SERVICE_SPRING_LOG_LEVEL:${CAF_LOG_LEVEL:WARN}}
    com.github.cafdataprocessing.services.staging: ${CAF_STAGING_SERVICE_LOG_LEVEL:${CAF_LOG_LEVEL:INFO}}
